### ISSUE TITLE
Compatibility with TerraFirmaCraft

### ISSUE THREAD

**Issue by Pentasis** [Meldexun/BetterDiving#46] opened 2019-11-19 11:49 UTC
**Enhancement**
Let underwater plants spawn in tfc:ocean and tfc:deep_ocean biomes.

**Versions**
Minecraft: 1.12.2

I added these biomes to the config and raised the height to accomodate tfc-terrain, but only the fish spawn, not the plants. This could be either related to the fact that TFC uses different water-blocks or gravel/sand-blocks?)

**Comment by Meldexun** [comment] 2019-11-21 21:55
I could try to add compatability but the problem is that the TerraFirmaCraft water destroys my blocks.

**Comment by Pentasis** [comment] 2019-11-21 21:58
Well, if it is too much work don't bother. It is a bit of a niche case. I can live without it :)

**Comment by Meldexun** [comment] 2020-04-09 23:37
Fixed in v1.5.0

**Closed by Meldexun** 2020-04-09 23:37 UTC
Labels: enhancement
