### ISSUE TITLE
Seamoth Visual Bug with another mod

### ISSUE THREAD

**Issue by jajajafeti** [Meldexun/BetterDiving#100] opened 2021-02-26 21:16 UTC
**Describe the bug**
If u sit in the Seamtoh you have a bar in front of your face (only visual). Which is the roof of the Seamoth.

![image](https://user-images.githubusercontent.com/61298096/109355581-b6eb8480-787f-11eb-86c6-ef4488623257.png)

**To Reproduce**
Sit in a Seamoth
and have the mod Shrink installed

**Versions**
Better Diving: 1.2.3
Forge: 36.0.42
Minecraft: 1.16.5

**Other**
Singleplayer:
Other mods (that are necessary to produce the bug): 
Shrink-1.16.4-1.0.7 - [https://www.curseforge.com/minecraft/mc-mods/shrink_](https://www.curseforge.com/minecraft/mc-mods/shrink_)

**Comment by JuicyCosmos** [comment] 2021-03-07 08:26
I don't think Shrink is needed to reproduce this issue. My modpack does not include Shrink, but also have the same issue. The sofacopter from CVM also has visual obtrusion(not a bug) when accelerating. I'm now just going to go 3rd person when driving.

**Comment by jajajafeti** [comment] 2021-03-07 17:47
Well it has to do something with it, caus I tested it while only having this two mods.

**Comment by VallenFrostweaver** [comment] 2021-05-17 09:09
This is due to the player being mounted too high in the seamoth. Go into F5 view to see yourself from the front. It becomes apparent.

**Comment by VallenFrostweaver** [comment] 2021-05-17 09:23
This is actually more than a visual bug as the player will still lose air supply - possibly due to the player head sticking out of the seamoth. See image below.
![image](https://user-images.githubusercontent.com/13642054/118465521-ddd88a80-b6f9-11eb-8d96-3b3f918865d0.png)

**Comment by Meldexun** [comment] 2021-05-17 14:33
Should be fixed in v1.16.5-1.2.4

Though this bug has nothing to do with you loosing oxygen while inside a seamoth. I guess the power cell of the seamoth is empty. If that is not the case then please create a new issue.

**Closed by Meldexun** 2021-05-17 14:33 UTC
Labels: bug
