### ISSUE TITLE
Compatability for the "Streams" mod?

### ISSUE THREAD

**Issue by Abo233** [Meldexun/BetterDiving#35] opened 2019-09-08 02:26 UTC
Lead to streams mod

I feel the water a little science

Under the waterfall will not be washed away。。

**Comment by Meldexun** [comment] 2019-10-26 18:10
Currently i'm not working on compatability.
Link to the mod: [Streams](https://www.curseforge.com/minecraft/mc-mods/streams)

**Comment by Meldexun** [comment] 2019-11-15 14:50
I don't understand what the problem is. When testing both mods together it seems to work fine. So unless someone can show me a problem with the streams mod i will close this.

**Closed** 2019-12-03 16:47 UTC
Labels: enhancement
