### ISSUE TITLE
Fish High Spawn

### ISSUE THREAD

**Issue by RodrigoTaipe93** [Meldexun/BetterDiving#103] opened 2021-03-15 06:12 UTC
Description:

Lots of fish spawn

**To Reproduce**
1. Just wait
2. Eventually they start spawning
3. PC can't handle so many fishes
.
.
.
4. No crash, just lots of fish

(adding my config file, just in case: https://pastebin.com/6ei5nQnY)

**Versions**
Better Diving: BetterDiving-1.12.2-1.5.8
Forge: 14.23.5.2855
Minecraft: 1.12.2

**Other**
Crash report (if one exists):
Latest log:
Singleplayer/Multiplayer: Singleplayer
Other mods (that are necessary to produce the bug): 
![2021-03-15_00 08 04](https://user-images.githubusercontent.com/12539074/111110900-60db3a00-852b-11eb-9378-1b4ab88d5f60.png)

Other mods (that are also installed):

**Comment by Meldexun** [comment] 2021-03-15 15:26
Duplicate of #78

**Closed by Meldexun** 2021-03-15 15:26 UTC
Labels: bug
