### ISSUE TITLE
Oxygen Config is still broken.

### ISSUE THREAD

**Issue by Boolyman** [Meldexun/BetterDiving#37] opened 2019-09-30 05:28 UTC
**Describe the bug**
Same as it has always been... the Oxygen capacity ignores the config changes.  Sometimes it happens, some times it doesnt.  Sometimes the GUI works properly, some times it doesn't.  As you can see in this screenshot, my Oxygen GUI say I still have 18 units of air left... and yet, I died of drowning.  Also, I am not even using the Holdyerbreath mod we made to be compatible with this mod anymore because each update you put out broke the compatibility.  So thats not a conflict here.

![2019-09-30 00_21_05-Greenshot](https://user-images.githubusercontent.com/24765883/65851500-a6487f00-e318-11e9-8987-2be83087348a.png)

**To Reproduce**
1. Go to the config file and change the Oxygen amounts.
2. Use legs to jump into water in game.
3. Place block around the grave you get when the config is ignored.
4. See error in the devs patch notes claiming this was fixed.

**Versions**
Better Diving:  1.3.91
Forge: 14.23.5.2838 
Minecraft 1.12.2

**Other**
Crash report (if one exists):
Other mods (that are necessary to produce the bug):

**Here is my config file:  https://pastebin.com/diyDeW2G
I can send you an export of my modpack if it will help you troubleshoot.**

**Comment by Meldexun** [comment] 2019-10-02 12:01
I'm not able to reproduce the bug.
Are you playing on a server or in singleplayer?
You could test it again and try to describe the steps to reproduce as exactly as possible.
It could also be a desync of client and server. So if you leave your world and enter it again it might work again.
If that all doesn't help me to understand the bug i don't know how to find a fix.

**Comment by Boolyman** [comment] 2019-10-04 23:43
I dont know how to reproduce it.  I just know I keep getting bug reports from people playing my pack, and its happened to me.  Really unfortunate since its such a big part of the pack.

**Comment by Meldexun** [comment] 2019-10-05 13:43
Ok. And when you encountered the bug were you swimming around the ocean? Especially near any blocks?
Because there is a bug where the oxygen can desync when swimming near air blocks but that one is already fixed in my workspace.

**Comment by Boolyman** [comment] 2019-10-07 06:48
It happened again, this time to a streamer.  Here is the video link... at 2hr 26mins into the video https://www.twitch.tv/videos/491323332

**Comment by Meldexun** [comment] 2019-10-07 17:26
Yes, it's the issue i described. The next update will come soon.

**Comment by Boolyman** [comment] 2019-10-07 20:01
Ok, ill keep an eye out for it.  This streamer was playing in hardcore mode and this made him lose his world.  You can imagine my embarrssment.

**Comment by Meldexun** [comment] 2019-10-08 16:25
I plan to release it before the 14th October.

**Comment by Meldexun** [comment] 2019-10-11 23:55
Fixed in v1.4.0

**Closed by Meldexun** 2019-10-11 23:55 UTC
Labels: bug
