### ISSUE TITLE
1.13 like movment bug

### ISSUE THREAD

**Issue by Pengu-Hunter** [Meldexun/BetterDiving#68] opened 2020-04-24 14:56 UTC
**Describe the bug**
If you hold down sprint while in deep enough water for the 1.13 like movment to activate then keep sprint held down whilst exiting water onto land then your character is bugged so that your camera is lower than normal and wherever your cursor is pointing you actualy interact with blocks one block below where you are looking, to fix the bug you need to go back into the water that is deep enough for the special movement then press and release the sprint button then leave the water.

**Versions**
Better Diving: All versions iv'e used including most recent as of this post (1.5.0
Forge: 14.23.5.2847
Minecraft: 1.12.2

**Comment by Meldexun** [comment] 2020-04-24 18:30
I don't know what you mean. When you sprint underwater your movement isn't changed unless you changed the config. I guess you mean the hitbox resizing when sprinting underwater. Though i can't reproduce what you are saying. So either give a better explanation or maybe record a video (preferably in third person with f3+b active so that i can see the hitbox/eye height)

**Comment by Pengu-Hunter** [comment] 2020-04-25 02:39
Sorry if my explanation was confusing or not enough and yes i do mean the hitbox resizing I've tried to reproduce the bug as i described and couldn't get the bug to occur so next time it happens I will take screen shots from third person with hitboxes shown.

**Comment by Meldexun** [comment] 2020-04-25 18:33
So because I updated the player resizing in v1.5.1 I will close this now. Just reopen the issue when it is happening again (with v1.5.1).

**Closed by Meldexun** 2020-04-25 18:33 UTC
Labels: bug
